version: '3.9'

services:
  database_ignit:
    image: postgres
    container_name: database_ignit
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ignit
      - POSTGRES_PASSWORD=ignit
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database_ignit
    depends_on:
      - database_ignit

volumes:
  pgdata:
    driver: local

